name: 京东自动签到领京豆

on:
  schedule:
    - cron: '0 0 * * *'     
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  UPLOAD_BESULT_DIR: true

jobs:
    jd_sign:
        runs-on: ubuntu-latest
        steps:
            - name: 切换到runner上
              uses: actions/checkout@v3
            
            - name: 下载"京东多合一签到脚本"
              run: wget https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
              
            - name: 安装nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '14'
                
            - name: 安装依赖
              run: |
                  npm install
                  npm i request -g

            - name: tsc编译ts脚本
              run: |
                  npm i -g typescript
                  tsc
                  echo 编译成功
                  ls

            - name: 执行脚本
              run: node ./index.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt
